# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-texlive/texlive-fontsextra/texlive-fontsextra-2009.ebuild,v 1.1 2010/01/11 03:15:47 aballier Exp $

TEXLIVE_MODULE_CONTENTS="Asana-Math albertus allrunes antiqua antp antt apl ar archaic arev ascii astro atqolive augie auncial-new aurical barcodes bayer bbding bbm bbm-macros bbold belleek bera blacklettert1 boisik bookhands braille brushscr calligra carolmin-ps ccicons cherokee clarendo cm-lgc cm-super cmbright cmll cmpica coronet courier-scaled cryst cyklop dancers dice dictsym dingbat doublestroke dozenal duerer duerer-latex ean ecc eco eiad eiad-ltx elvish epigrafica epsdice esvect eulervm euxm feyn fge foekfont fonetika fourier fouriernc frcursive garamond genealogy gentium gfsartemisia gfsbodoni gfscomplutum gfsdidot gfsneohellenic gfssolomos gnu-freefont gothic greenpoint groff grotesq hands hfbright hfoldsty ifsym inconsolata initials iwona jablantile junicode kixfont knuthotherfonts kpfonts kurier lettrgth lfb libertine libris linearA logic lxfonts ly1 marigold mathabx mathdesign mnsymbol nkarta ocherokee ogham oinuit optima orkhun osmanian pacioli pclnfss phaistos phonetic pigpen psafm punk recycle sauter sauterfonts semaphor simpsons skull staves tapir tengwarscript tpslifonts trajan umtypewriter univers universa venturisadf wsuipa yfonts zefonts collection-fontsextra
"
TEXLIVE_MODULE_DOC_CONTENTS="Asana-Math.doc allrunes.doc antiqua.doc antp.doc antt.doc ar.doc archaic.doc arev.doc ascii.doc astro.doc augie.doc auncial-new.doc aurical.doc barcodes.doc bayer.doc bbding.doc bbm.doc bbm-macros.doc bbold.doc belleek.doc bera.doc blacklettert1.doc boisik.doc bookhands.doc braille.doc brushscr.doc calligra.doc carolmin-ps.doc ccicons.doc cm-lgc.doc cm-super.doc cmbright.doc cmll.doc cmpica.doc courier-scaled.doc cryst.doc cyklop.doc dice.doc dictsym.doc dingbat.doc doublestroke.doc dozenal.doc duerer.doc duerer-latex.doc ean.doc ecc.doc eco.doc eiad.doc eiad-ltx.doc elvish.doc epigrafica.doc epsdice.doc esvect.doc eulervm.doc feyn.doc fge.doc foekfont.doc fonetika.doc fourier.doc fouriernc.doc frcursive.doc genealogy.doc gentium.doc gfsartemisia.doc gfsbodoni.doc gfscomplutum.doc gfsdidot.doc gfsneohellenic.doc gfssolomos.doc gnu-freefont.doc gothic.doc greenpoint.doc grotesq.doc hfbright.doc hfoldsty.doc ifsym.doc inconsolata.doc initials.doc iwona.doc jablantile.doc junicode.doc kixfont.doc kpfonts.doc kurier.doc lfb.doc libertine.doc libris.doc linearA.doc lxfonts.doc ly1.doc mathabx.doc mathdesign.doc mnsymbol.doc nkarta.doc ocherokee.doc ogham.doc oinuit.doc orkhun.doc pacioli.doc pclnfss.doc phaistos.doc phonetic.doc pigpen.doc recycle.doc sauterfonts.doc semaphor.doc staves.doc tapir.doc tengwarscript.doc tpslifonts.doc trajan.doc universa.doc venturisadf.doc wsuipa.doc yfonts.doc zefonts.doc "
TEXLIVE_MODULE_SRC_CONTENTS="allrunes.source apl.source archaic.source arev.source ascii.source augie.source auncial-new.source barcodes.source bayer.source bbding.source bbm-macros.source bbold.source belleek.source blacklettert1.source bookhands.source braille.source brushscr.source ccicons.source cmbright.source cmll.source dingbat.source dozenal.source eco.source eiad-ltx.source epsdice.source esvect.source eulervm.source feyn.source fge.source fourier.source frcursive.source hfbright.source hfoldsty.source kpfonts.source libris.source linearA.source mnsymbol.source nkarta.source oinuit.source pacioli.source pclnfss.source phaistos.source sauterfonts.source skull.source staves.source tengwarscript.source trajan.source universa.source venturisadf.source yfonts.source "
inherit texlive-module
DESCRIPTION="TeXLive Extra fonts"

LICENSE="GPL-2 as-is BSD freedist GPL-1 GPL-2 GPL-3 LPPL-1.3 OFL public-domain TeX "
SLOT="0"
KEYWORDS="~amd64-linux ~x86-linux ~ppc-macos ~x86-macos ~sparc-solaris ~x86-solaris"
IUSE=""
DEPEND=">=dev-texlive/texlive-basic-2009
!=dev-texlive/texlive-langpolish-2007*
"
RDEPEND="${DEPEND} "
