#!/sbin/runscript

PHP_FPM_CONF="@GENTOO_PORTAGE_EPREFIX@/etc/php/fpm-php5/php-fpm.conf"

opts="depend start stop reload"

depend() {
	need net
	use apache2 lighttpd nginx
}

start() {
	ebegin "Starting PHP FastCGI server"
	start-stop-daemon --start --exec @GENTOO_PORTAGE_EPREFIX@/usr/bin/php-fpm -- -y "${PHP_FPM_CONF}"
	eend $?
}

stop() {
	ebegin "Stopping PHP FastCGI server"
	start-stop-daemon --stop --name php-fpm
	eend $?
}
