#!/sbin/runscript
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/git/files/git-daemon.initd,v 1.5 2008/11/24 09:24:45 robbat2 Exp $

depend() {
	need net
	use logger
}

start() {
	ebegin "Starting git-daemon"
		start-stop-daemon --start --quiet --background \
		--exec /usr/bin/git -- daemon \
			--pid-file=/var/run/git-daemon.pid \
			--user=${GIT_USER} --group=${GIT_GROUP} \
			${GITDAEMON_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping git-daemon"
		start-stop-daemon --stop --quiet \
		--pidfile /var/run/git-daemon.pid
	eend $?
}
