--- Makefile	2007-05-24 10:24:48.000000000 -0400
+++ Makefile	2007-05-24 10:25:41.000000000 -0400
@@ -19,7 +19,7 @@
 #CFLAGS   += -DEBUG -g
 #CFLAGS   += -Os -DOPTIMIZE_FOR_SIZE=2 -falign-functions=2 -falign-jumps=2 -falign-labels=2 -falign-loops=2
 #LDFLAGS  := -pie
-LDFLAGS   += $(shell echo | $(CC) -dM -E - | grep -q ' __FreeBSD__' && echo '-lkvm')
+LIBADD    += $(shell echo | $(CC) -dM -E - | grep -q ' __FreeBSD__' && echo '-lkvm')
 DESTDIR   :=
 PREFIX    := $(DESTDIR)/usr
 STRIP     := strip
@@ -27,7 +27,8 @@
 CP        := cp
 
 ifndef STATIC
-LDFLAGS   += -Wl,--export-dynamic $(shell echo | $(CC) -dM -E - | grep -q ' __linux__' && echo '-ldl')
+LDFLAGS   += -Wl,--export-dynamic
+LIBADD    += $(shell echo | $(CC) -dM -E - | grep -q ' __linux__' && echo '-ldl')
 else
 CFLAGS    += -DSTATIC
 endif
@@ -63,13 +64,13 @@
 ifeq ($(subst s,,$(MAKEFLAGS)),$(MAKEFLAGS))
 	@echo $(foreach a,$(APPLETS), : $a) :
 ifndef V
-	@echo $(CC) $(CFLAGS) $(PYFLAGS) $(LDFLAGS) main.c -o q
+	@echo $(CC) $(CFLAGS) $(PYFLAGS) $(LDFLAGS) main.c -o q $(LIBADD)
 endif
 endif
 ifndef V
-	@$(CC) $(WFLAGS) $(PYFLAGS) $(LDFLAGS) $(CFLAGS) $(HFLAGS) main.c -o q
+	@$(CC) $(WFLAGS) $(PYFLAGS) $(LDFLAGS) $(CFLAGS) $(HFLAGS) main.c -o q $(LIBADD)
 else
-	$(CC) $(WFLAGS) $(PYFLAGS) $(LDFLAGS) $(CFLAGS) $(HFLAGS) main.c -o q
+	$(CC) $(WFLAGS) $(PYFLAGS) $(LDFLAGS) $(CFLAGS) $(HFLAGS) main.c -o q $(LIBADD)
 endif
 
 .depend: $(SRC)
