#!/sbin/runscript
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/git/files/git-daemon.initd,v 1.6 2008/11/27 20:33:34 robbat2 Exp $

PIDFILE=/var/run/git-daemon.pid

depend() {
	need net
	use logger
}

start() {
	[ -e /lib/librc.so ] || BL1_COMPAT="--name git-daemon"
	ebegin "Starting git-daemon"
		start-stop-daemon --start --quiet --background \
		--pidfile ${PIDFILE} ${BL1_COMPAT} \
		--exec /usr/bin/git -- daemon \
			--pid-file=${PIDFILE} \
			--user=${GIT_USER} --group=${GIT_GROUP} \
			${GITDAEMON_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping git-daemon"
		start-stop-daemon --stop --quiet \
		--pidfile ${PIDFILE}
	eend $?
}
